name: Hut Availability Checker

on:
  workflow_dispatch:
    inputs:
      huts:
        description: 'Comma-separated hut IDs (e.g. 150,603)'
        required: true
        default: '150'
      dates:
        description: 'Date ranges JSON string (e.g. [{"arrivalDate":"11.07.2025","departureDate":"12.07.2025"}])'
        required: true
        default: '[{"arrivalDate":"11.07.2025","departureDate":"12.07.2025"}]'

jobs:
  check-availability:
    runs-on: ubuntu-latest

    container:
      image: python:3.11-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests

      - name: Run availability checker
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          HUTS: ${{ github.event.inputs.huts }}
          DATES: ${{ github.event.inputs.dates }}
        run: python check_availability.py
